Repository lnwdevelopers007/job-applier-3000, pull requests merged in 2025-09, with the labels that each got.

#62 Backend schema
  server/internal/controller/job_controller.go
  server/internal/controller/router.go
  server/internal/schema/company.go
  server/internal/schema/company_test.go
  server/internal/schema/file.go
  server/internal/schema/file_test.go
  server/internal/schema/job.go
  server/internal/schema/job_application.go
  server/internal/schema/job_application_test.go
  server/internal/schema/job_schema.go
  server/internal/schema/job_seeker.go
  server/internal/schema/job_seeker_test.go
  server/internal/schema/job_test.go
  server/internal/schema/note.go
  server/internal/schema/note_test.go
  server/internal/schema/test_utils.go
  server/internal/schema/user.go
  server/internal/tests/job_test.go
Labels: backend

#90 Backend oauth
  client/bun.lock
  client/package.json
  client/src/routes/callback/+page.svelte
  client/src/routes/callback/apifetch.ts
  server/.env.example
  server/config/config.go
  server/go.mod
  server/go.sum
  server/internal/auth/auth.go
  server/internal/auth/generate_tokens.go
  server/internal/auth/refresh_token.go
  server/internal/controller/router.go
Labels: enhancement, backend

#96 Frontend job posting form, edit posting form and dashboard.
  client/eslint.config.js
  client/src/routes/company/create/+page.svelte
  client/src/routes/company/dashboard/+page.svelte
  client/src/routes/company/edit/[id]/+page.svelte
  server/internal/controller/job_controller.go
  server/internal/controller/router.go
  server/internal/schema/job.go
  server/internal/schema/job_test.go
  server/internal/tests/job_test.go
Labels: frontend, backend

#109 Frontend job dashboard page Search bar and Filter buttons
  client/bun.lock
  client/package.json
  client/src/lib/utils/SafeHTML.svelte
  client/src/routes/app/jobs/+page.svelte
  server/internal/controller/job_controller.go
Labels: full-stack
